name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of artifact
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: The result of workflow
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -R
      - name: Check secret
        run: |
          if [ "$SECRET_VALUE" = "Some_Secret" ]; then echo "Secret matches"; else echo "Secret does not match"; fi
        env:
          SECRET_VALUE: ${{ secrets.some-secret }}
      - name: Output info
        run: echo "Deploying..."
      - name: Result output
        id: set-result
        run: echo "step-result=success" >>$GITHUB_OUTPUT

